<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="2" failed="1" total="3" passed="0">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="1210721" started-at="2016-04-07T13:43:34Z" finished-at="2016-04-07T14:03:45Z">
    <groups>
    </groups>
    <test name="Default test" duration-ms="1210721" started-at="2016-04-07T13:43:34Z" finished-at="2016-04-07T14:03:45Z">
      <class name="ALLie_AutoTests.TestSuite">
        <test-method status="PASS" signature="setUp()[pri:0, instance:ALLie_AutoTests.TestSuite@28864e92]" name="setUp" is-config="true" duration-ms="47264" started-at="2016-04-07T18:43:34Z" finished-at="2016-04-07T18:44:21Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method status="FAIL" signature="Ride()[pri:0, instance:ALLie_AutoTests.TestSuite@28864e92]" name="Ride" duration-ms="1125601" started-at="2016-04-07T18:44:21Z" finished-at="2016-04-07T19:03:07Z">
          <exception class="org.openqa.selenium.NoSuchElementException">
            <message>
              <![CDATA[An element could not be located on the page using the given search parameters. (WARNING: The server did not provide any stacktrace information)
Command duration or timeout: 7.20 seconds
For documentation on this error, please visit: http://seleniumhq.org/exceptions/no_such_element.html
Build info: version: '2.45.0', revision: '32a636c', time: '2015-03-05 22:01:35'
System info: host: 'Dmitriys-MacBook-Pro-3.local', ip: '10.0.2.15', os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.11.3', java.version: '1.8.0_45'
Driver info: io.appium.java_client.ios.IOSDriver
Capabilities [{app=com.icrtech.allie, networkConnectionEnabled=false, warnings={}, databaseEnabled=false, deviceName=iPad Air, platform=MAC, desired={app=com.icrtech.allie, appium-version=1.0, sendKeyStrategy=grouped, newCommandTimeout=999999, platformVersion=8.2, waitForAppScript=$.delay(30000); $.acceptAlert(), platformName=iOS, deviceName=iPad Air}, appium-version=1.0, sendKeyStrategy=grouped, newCommandTimeout=999999, platformVersion=8.2, webStorageEnabled=false, locationContextEnabled=false, browserName=iOS, takesScreenshot=true, waitForAppScript=$.delay(30000); $.acceptAlert(), javascriptEnabled=true, platformName=iOS}]
Session ID: 5254cc82-7efc-4187-9d95-fd5ddb60d867
*** Element info: {Using=xpath, value=//UIAApplication[1]/UIAWindow[1]/UIATableView[2]/UIATableCell[1]/UIAButton[1]}]]>
            </message>
            <full-stacktrace>
              <![CDATA[org.openqa.selenium.NoSuchElementException: An element could not be located on the page using the given search parameters. (WARNING: The server did not provide any stacktrace information)
Command duration or timeout: 7.20 seconds
For documentation on this error, please visit: http://seleniumhq.org/exceptions/no_such_element.html
Build info: version: '2.45.0', revision: '32a636c', time: '2015-03-05 22:01:35'
System info: host: 'Dmitriys-MacBook-Pro-3.local', ip: '10.0.2.15', os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.11.3', java.version: '1.8.0_45'
Driver info: io.appium.java_client.ios.IOSDriver
Capabilities [{app=com.icrtech.allie, networkConnectionEnabled=false, warnings={}, databaseEnabled=false, deviceName=iPad Air, platform=MAC, desired={app=com.icrtech.allie, appium-version=1.0, sendKeyStrategy=grouped, newCommandTimeout=999999, platformVersion=8.2, waitForAppScript=$.delay(30000); $.acceptAlert(), platformName=iOS, deviceName=iPad Air}, appium-version=1.0, sendKeyStrategy=grouped, newCommandTimeout=999999, platformVersion=8.2, webStorageEnabled=false, locationContextEnabled=false, browserName=iOS, takesScreenshot=true, waitForAppScript=$.delay(30000); $.acceptAlert(), javascriptEnabled=true, platformName=iOS}]
Session ID: 5254cc82-7efc-4187-9d95-fd5ddb60d867
*** Element info: {Using=xpath, value=//UIAApplication[1]/UIAWindow[1]/UIATableView[2]/UIATableCell[1]/UIAButton[1]}
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:422)
	at org.openqa.selenium.remote.ErrorHandler.createThrowable(ErrorHandler.java:204)
	at org.openqa.selenium.remote.ErrorHandler.throwIfResponseFailed(ErrorHandler.java:156)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:599)
	at io.appium.java_client.AppiumDriver.execute(AppiumDriver.java:216)
	at org.openqa.selenium.remote.RemoteWebDriver.findElement(RemoteWebDriver.java:352)
	at org.openqa.selenium.remote.RemoteWebDriver.findElementByXPath(RemoteWebDriver.java:449)
	at io.appium.java_client.AppiumDriver.findElementByXPath(AppiumDriver.java:107)
	at io.appium.java_client.AppiumDriver.findElementByXPath(AppiumDriver.java:1)
	at org.openqa.selenium.By$ByXPath.findElement(By.java:357)
	at org.openqa.selenium.remote.RemoteWebDriver.findElement(RemoteWebDriver.java:344)
	at io.appium.java_client.AppiumDriver.findElement(AppiumDriver.java:75)
	at ALLie_AutoTests.Basemethods.Sharing(Basemethods.java:832)
	at ALLie_AutoTests.AccountScreen.AccountCheck(AccountScreen.java:104)
	at ALLie_AutoTests.TestSuite.Ride(TestSuite.java:43)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:822)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1130)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:113)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:206)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:177)
]]>
            </full-stacktrace>
          </exception> <!-- org.openqa.selenium.NoSuchElementException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- Ride -->
        <test-method status="PASS" signature="catchExceptions(org.testng.ITestResult)[pri:0, instance:ALLie_AutoTests.TestSuite@28864e92]" name="catchExceptions" is-config="true" duration-ms="20965" started-at="2016-04-07T19:03:07Z" finished-at="2016-04-07T19:03:28Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=Ride status=FAILURE method=TestSuite.Ride()[pri:0, instance:ALLie_AutoTests.TestSuite@28864e92] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- catchExceptions -->
        <test-method status="FAIL" signature="setUp()[pri:0, instance:ALLie_AutoTests.TestSuite@28864e92]" name="setUp" is-config="true" duration-ms="0" started-at="2016-04-07T19:03:28Z" finished-at="2016-04-07T19:03:28Z">
          <exception class="org.openqa.selenium.remote.UnreachableBrowserException">
            <message>
              <![CDATA[Could not start a new session. Possible causes are invalid address of the remote server or browser start-up failure.
Build info: version: '2.45.0', revision: '32a636c', time: '2015-03-05 22:01:35'
System info: host: 'Dmitriys-MacBook-Pro-3.local', ip: '10.0.2.15', os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.11.3', java.version: '1.8.0_45'
Driver info: driver.version: IOSDriver]]>
            </message>
            <full-stacktrace>
              <![CDATA[org.openqa.selenium.remote.UnreachableBrowserException: Could not start a new session. Possible causes are invalid address of the remote server or browser start-up failure.
Build info: version: '2.45.0', revision: '32a636c', time: '2015-03-05 22:01:35'
System info: host: 'Dmitriys-MacBook-Pro-3.local', ip: '10.0.2.15', os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.11.3', java.version: '1.8.0_45'
Driver info: driver.version: IOSDriver
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:593)
	at io.appium.java_client.AppiumDriver.execute(AppiumDriver.java:216)
	at org.openqa.selenium.remote.RemoteWebDriver.startSession(RemoteWebDriver.java:240)
	at org.openqa.selenium.remote.RemoteWebDriver.<init>(RemoteWebDriver.java:126)
	at org.openqa.selenium.remote.RemoteWebDriver.<init>(RemoteWebDriver.java:153)
	at io.appium.java_client.AppiumDriver.<init>(AppiumDriver.java:145)
	at io.appium.java_client.ios.IOSDriver.<init>(IOSDriver.java:24)
	at ALLie_AutoTests.BaseTest.setUp(BaseTest.java:61)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:514)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:215)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:589)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:822)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1130)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:113)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:206)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:177)
Caused by: org.apache.http.conn.HttpHostConnectException: Connect to 127.0.0.1:4723 [/127.0.0.1] failed: Connection refused
	at org.apache.http.impl.conn.HttpClientConnectionOperator.connect(HttpClientConnectionOperator.java:142)
	at org.apache.http.impl.conn.PoolingHttpClientConnectionManager.connect(PoolingHttpClientConnectionManager.java:319)
	at org.apache.http.impl.execchain.MainClientExec.establishRoute(MainClientExec.java:363)
	at org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:219)
	at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:195)
	at org.apache.http.impl.execchain.RetryExec.execute(RetryExec.java:86)
	at org.apache.http.impl.execchain.RedirectExec.execute(RedirectExec.java:108)
	at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:184)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:72)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:57)
	at org.openqa.selenium.remote.internal.ApacheHttpClient.fallBackExecute(ApacheHttpClient.java:144)
	at org.openqa.selenium.remote.internal.ApacheHttpClient.execute(ApacheHttpClient.java:72)
	at org.openqa.selenium.remote.HttpCommandExecutor.execute(HttpCommandExecutor.java:133)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:572)
	... 33 more
Caused by: java.net.ConnectException: Connection refused
	at java.net.PlainSocketImpl.socketConnect(Native Method)
	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:345)
	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
	at java.net.Socket.connect(Socket.java:589)
	at org.apache.http.conn.socket.PlainConnectionSocketFactory.connectSocket(PlainConnectionSocketFactory.java:72)
	at org.apache.http.impl.conn.HttpClientConnectionOperator.connect(HttpClientConnectionOperator.java:125)
	... 46 more
]]>
            </full-stacktrace>
          </exception> <!-- org.openqa.selenium.remote.UnreachableBrowserException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method status="SKIP" signature="Schedul_()[pri:0, instance:ALLie_AutoTests.TestSuite@28864e92]" name="Schedul_" duration-ms="1" started-at="2016-04-07T19:03:45Z" finished-at="2016-04-07T19:03:45Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- Schedul_ -->
        <test-method status="PASS" signature="catchExceptions(org.testng.ITestResult)[pri:0, instance:ALLie_AutoTests.TestSuite@28864e92]" name="catchExceptions" is-config="true" duration-ms="0" started-at="2016-04-07T19:03:45Z" finished-at="2016-04-07T19:03:45Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=Schedul_ status=SKIP method=TestSuite.Schedul_()[pri:0, instance:ALLie_AutoTests.TestSuite@28864e92] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- catchExceptions -->
        <test-method status="SKIP" signature="setUp()[pri:0, instance:ALLie_AutoTests.TestSuite@28864e92]" name="setUp" is-config="true" duration-ms="0" started-at="2016-04-07T19:03:45Z" finished-at="2016-04-07T19:03:45Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method status="PASS" signature="catchExceptions(org.testng.ITestResult)[pri:0, instance:ALLie_AutoTests.TestSuite@28864e92]" name="catchExceptions" is-config="true" duration-ms="1" started-at="2016-04-07T19:03:45Z" finished-at="2016-04-07T19:03:45Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=Schedul_2 status=SKIP method=TestSuite.Schedul_2()[pri:0, instance:ALLie_AutoTests.TestSuite@28864e92] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- catchExceptions -->
        <test-method status="SKIP" signature="Schedul_2()[pri:0, instance:ALLie_AutoTests.TestSuite@28864e92]" name="Schedul_2" duration-ms="0" started-at="2016-04-07T19:03:45Z" finished-at="2016-04-07T19:03:45Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- Schedul_2 -->
      </class> <!-- ALLie_AutoTests.TestSuite -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
